---
apiVersion: v2
name: vcluster-hpm
description: Customized vcluster-hostpath-mapper

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: vcluster-hpm
    version: 0.1.1
    repository: https://charts.loft.sh
